// DO NOT EDIT THIS FILE. 
// Any modifications to this file will result in an automatic failure of the task.
import PatientCard from './PatientCard';

export default function PatientList({ patients }) {
  if (!patients || patients.length === 0) {
    return (
      <div style={{ padding: '20px', textAlign: 'center', backgroundColor: '#f9f9f9' }}>
        <p>No patients found matching your search.</p>
      </div>
    );
  }

  return (
    <div>
      {patients.map((patient) => (
        <PatientCard key={patient.id} patient={patient} />
      ))}
    </div>
  );
}
