// DO NOT EDIT THIS FILE. 
// Any modifications to this file will result in an automatic failure of the task.

export default function PatientCard({ patient }) {
  return (
    <div style={{ border: '1px solid #ccc', padding: '12px', marginBottom: '8px', borderRadius: '4px' }}>
      <h4 style={{ margin: '0 0 8px 0' }}>{patient.name} (ID: {patient.id})</h4>
      <p style={{ margin: '4px 0' }}><strong>Status:</strong> {patient.status}</p>
      <p style={{ margin: '4px 0' }}><strong>Balance:</strong> PHP {patient.balance.toFixed(2)}</p>
      <p style={{ margin: '4px 0' }}><strong>Ward:</strong> {patient.ward}</p>
    </div>
  );
}
