// DO NOT EDIT THIS FILE. 
// Any modifications to this file will result in an automatic failure of the task.

export default function SearchBar({ searchQuery, onSearchChange }) {
  return (
    <div style={{ marginBottom: '20px' }}>
      <label style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>
        Patient Search
      </label>
      <input
        type="text"
        placeholder="Search patient by name..."
        value={searchQuery}
        onChange={(e) => onSearchChange(e.target.value)}
        style={{ padding: '8px', width: '100%', boxSizing: 'border-box' }}
      />
    </div>
  );
}
